clear;
clc;
close all;

paths = project_paths();

%% 1. Load previously generated linear model

load(fullfile(paths.Models,"cartpole_linear_model.mat"));

continuousLinearSystem = ss( ...
    A, ...
    B, ...
    eye(4), ...
    zeros(4,1));

%% 2. Comparison settings

initialAnglesDeg = [1, 3, 6, 10];

% Use a short interval because the open-loop system is unstable.
simulationDuration = 0.4;

time = (0:p.dt:simulationDuration)';

zeroInput = zeros(size(time));

numberOfTests = numel(initialAnglesDeg);

angleRMSE = zeros(numberOfTests,1);
maximumAngleError = zeros(numberOfTests,1);
finalNonlinearAngle = zeros(numberOfTests,1);
finalLinearAngle = zeros(numberOfTests,1);

nonlinearAngleResults = cell(numberOfTests,1);
linearAngleResults = cell(numberOfTests,1);

%% 3. Create figure

figure( ...
    "Name", ...
    "Linear and Nonlinear CartPole Comparison");

tiledlayout(2,2);

%% 4. Run comparison

for testIndex = 1:numberOfTests

    initialAngleDeg = initialAnglesDeg(testIndex);

    initialState = [
        0
        0
        deg2rad(initialAngleDeg)
        0
    ];

    %% Nonlinear simulation

    odeOptions = odeset( ...
        "RelTol",1e-10, ...
        "AbsTol",1e-12);

    [timeNonlinear,stateNonlinear] = ode45( ...
        @(t,s) cartpole_dynamics(t,s,0,p), ...
        time, ...
        initialState, ...
        odeOptions);

    %% Linear simulation

    [stateLinear,timeLinear] = lsim( ...
        continuousLinearSystem, ...
        zeroInput, ...
        time, ...
        initialState);

    %% Extract pole angles

    nonlinearAngleDeg = rad2deg(stateNonlinear(:,3));
    linearAngleDeg = rad2deg(stateLinear(:,3));

    nonlinearAngleResults{testIndex} = nonlinearAngleDeg;
    linearAngleResults{testIndex} = linearAngleDeg;

    %% Calculate model error

    angleErrorDeg = ...
        nonlinearAngleDeg - linearAngleDeg;

    angleRMSE(testIndex) = sqrt( ...
        mean(angleErrorDeg.^2));

    maximumAngleError(testIndex) = ...
        max(abs(angleErrorDeg));

    finalNonlinearAngle(testIndex) = ...
        nonlinearAngleDeg(end);

    finalLinearAngle(testIndex) = ...
        linearAngleDeg(end);

    %% Plot

    nexttile;

    plot( ...
        timeNonlinear, ...
        nonlinearAngleDeg, ...
        "b-", ...
        "LineWidth",1.8);

    hold on;

    plot( ...
        timeLinear, ...
        linearAngleDeg, ...
        "r--", ...
        "LineWidth",1.8);

    yline( ...
        rad2deg(p.angle_limit), ...
        "k:", ...
        "12 deg limit");

    yline( ...
        -rad2deg(p.angle_limit), ...
        "k:");

    grid on;

    xlabel("Time [s]");
    ylabel("Pole angle [deg]");

    title( ...
        sprintf( ...
        "Initial angle = %g deg", ...
        initialAngleDeg));

    legend( ...
        "Nonlinear", ...
        "Linear", ...
        "Location","northwest");
end

sgtitle( ...
    "Open-Loop Linear Approximation Accuracy");

%% 5. Print result table

comparisonTable = table( ...
    initialAnglesDeg', ...
    finalNonlinearAngle, ...
    finalLinearAngle, ...
    angleRMSE, ...
    maximumAngleError, ...
    VariableNames=[ ...
        "InitialAngleDeg", ...
        "FinalNonlinearDeg", ...
        "FinalLinearDeg", ...
        "AngleRMSEDeg", ...
        "MaximumErrorDeg" ...
    ]);

disp(comparisonTable);

%% 6. Plot approximation error

figure( ...
    "Name", ...
    "Linearization Error");

hold on;

for testIndex = 1:numberOfTests

    errorDeg = ...
        nonlinearAngleResults{testIndex} ...
        - linearAngleResults{testIndex};

    plot( ...
        time, ...
        errorDeg, ...
        "LineWidth",1.5, ...
        "DisplayName", ...
        sprintf("%g deg initial", ...
        initialAnglesDeg(testIndex)));
end

grid on;
xlabel("Time [s]");
ylabel("Nonlinear - Linear angle [deg]");
title("Linearization Error");
legend("Location","best");

%% 7. Save results

writetable( ...
    comparisonTable, ...
    fullfile(paths.Tables,"linearization_comparison.csv"));

fprintf( ...
    "Saved: %s\n", ...
    fullfile(paths.Tables,"linearization_comparison.csv"));
