function nextState = rk4_step(state,force,dt,p)
% RK4_STEP One fixed-step fourth-order Runge-Kutta integration.
%
% The input force remains constant during one control interval.

k1 = cartpole_dynamics( ...
    0, ...
    state, ...
    force, ...
    p);

k2 = cartpole_dynamics( ...
    0, ...
    state + 0.5*dt*k1, ...
    force, ...
    p);

k3 = cartpole_dynamics( ...
    0, ...
    state + 0.5*dt*k2, ...
    force, ...
    p);

k4 = cartpole_dynamics( ...
    0, ...
    state + dt*k3, ...
    force, ...
    p);

nextState = state ...
    + (dt/6)*(k1 + 2*k2 + 2*k3 + k4);
end