clear;
clc;
close all;

paths = project_paths();

rng(42,"twister");

%% 1. Create RL environment

env = create_cartpole_rl_environment();

validateEnvironment(env);

observationInfo = ...
    getObservationInfo(env);

actionInfo = ...
    getActionInfo(env);

%% 2. Initialize actor and critic networks

initializationOptions = ...
    rlAgentInitializationOptions( ...
    NumHiddenUnit=64, ...
    Normalization="none");

%% 3. Configure PPO algorithm

agentOptions = ...
    rlPPOAgentOptions( ...
    SampleTime=0.02, ...
    DiscountFactor=0.99, ...
    ExperienceHorizon=1024, ...
    MiniBatchSize=128, ...
    NumEpoch=10, ...
    ClipFactor=0.2, ...
    AdvantageEstimateMethod="gae", ...
    GAEFactor=0.95, ...
    EntropyLossWeight=0.01, ...
    NormalizedAdvantageMethod="current");

agentOptions.ActorOptimizerOptions.LearnRate = ...
    3e-4;

agentOptions.CriticOptimizerOptions.LearnRate = ...
    1e-3;

%% 4. Create PPO agent

agent = ...
    rlPPOAgent( ...
    observationInfo, ...
    actionInfo, ...
    initializationOptions, ...
    agentOptions);

%% 5. Configure training

trainingOptions = ...
    rlTrainingOptions( ...
    MaxEpisodes=1500, ...
    MaxStepsPerEpisode=500, ...
    ScoreAveragingWindowLength=50, ...
    StopTrainingCriteria="AverageReward", ...
    StopTrainingValue=450, ...
    Plots="training-progress", ...
    Verbose=true, ...
    UseParallel=false);

%% 6. Train agent

trainingStats = ...
    train( ...
    agent, ...
    env, ...
    trainingOptions);

%% 7. Save result

save( ...
    fullfile(paths.Models,"ppo_cartpole_trained.mat"), ...
    "agent", ...
    "trainingStats", ...
    "agentOptions", ...
    "trainingOptions");
